config/routes.rb
Lsssp::Application.routes.draw do

  resources :userexaminations

  resources :payments

  resources :examinations

  resources :questionbanks

  resources :subjects

  resources :users
  
  resources :user_sessions
  match 'login' => "user_sessions#new",      :as => :login
  match 'logout' => "user_sessions#destroy", :as => :logout
  
  resources :registrations

#  get "subjects/index"
#  get "subjects/new"
#  match "admin/subjects" => "subjects#index", :as => :subject
#  match "admin/subjects/new" =>"subjects#new", :as => :new_subject

  
  root :to => "user_sessions#new"
    
  match ':controller(/:action(/:id(.:format)))'
end

app/models/activetest.rb
class Activetest < ActiveRecord::Base

end

app/models/activexam.rb
class Activexam < ActiveRecord::Base
end

app/models/assignment.rb
class Assignment < ActiveRecord::Base
  belongs_to :user
  belongs_to :role
end

app/models/examination.rb
class Examination < ActiveRecord::Base
end

app/models/payment.rb
class Payment < ActiveRecord::Base
end

app/models/questionbank.rb
class Questionbank < ActiveRecord::Base
	belongs_to :subject
	
#	has_attached_file :question_image
end

app/models/registration.rb
class Registration < ActiveRecord::Base
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_many :assignments
  has_many :users, :through => :assignments
end

app/models/subject.rb
class Subject < ActiveRecord::Base
	has_many :questionbanks,:dependent=>:destroy
end

app/models/user.rb
class User < ActiveRecord::Base
 acts_as_authentic
  has_many :assignments
  has_many :roles, :through => :assignments


  def role_symbols
    roles.map do |role|
      role.name.underscore.to_sym
    end
  end

end

app/models/user_session.rb
class UserSession < Authlogic::Session::Base
  def to_key
    new_record? ? nil : [ self.send(self.class.primary_key) ]
  end
  
end

app/models/userexamination.rb
class Userexamination < ActiveRecord::Base
	belongs_to :examination
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  layout 'admin'

  #before_filter :require_no_user, :only => [:new, :create]
  before_filter :require_user, :only => [:index,:show, :edit, :update]
  def index

    @users = User.all #paginate :page => params[:page], :per_page=>10,:order => 'created_at DESC'
  end
  
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(params[:user])
    @user.created_by = @created_by
    respond_to do |format|
      if @user.save 
      	#send mail
        UserMailer.welcome_email(@user).deliver
        format.html { redirect_to(users_path, :notice => 'User was successfully created.') }    
      else
        format.html { render :action => "new" }
      end
    end
  end
  
  def show
    @user = User.find(params[:id])
  end
  
  def edit
    @user = User.find(params[:id])
  end
  
  def update
    @user = User.find(params[:id])
#    params[:user][:role_ids] ||= []
    
    @user.updated_by = @updated_by
    respond_to do |format|
      if @user.update_attributes(params[:user])     
        format.html { redirect_to(users_path, :notice => 'User was successfully updated.') }
      else
        format.html { render :action => "edit" }
      end
    end
  end
  
    def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to(users_url) }
      format.xml  { head :ok }
    end
  end
  
  
 
end

app/helpers/activetests_helper.rb
module ActivetestsHelper
end

app/helpers/activexam_helper.rb
module ActivexamHelper
end

app/helpers/adminindex_helper.rb
module AdminindexHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  
  def admin_tabs
    html = ''
    super_admin = Role.find_by_name('super_admin')
    admin = Role.find_by_name('admin')
    if current_user.roles.include?(super_admin) 
      
      html << "<li>"
      html << link_to('Users',{:controller=>'user',:action=>'index'},:class=>(current_page?(:controller=>'user',:action=>'index') ? "users selected" : ""))
      html << "</li>"


            
    elsif current_user.roles.include?(admin) 
      
      html <<  '<li>'
      html << link_to('Module',{:controller=>'subjects',:action=>'index'},:class=>(current_page?(:controller=>'subjects',:action=>'index') ? "subjects selected" : ""))
      html << '</li>'
     
      html <<  '<li>'
      html << link_to('Examination',{:controller=>'examinations',:action=>'index'},:class=>(current_page?(:controller=>'examinations',:action=>'index') ? "examinations selected" : ""))
      html << '</li>'
      
      html <<  '<li>'
      html << link_to('Payment',{:controller=>'payments',:action=>'index'},:class=>(current_page?(:controller=>'payments',:action=>'index') ? "payments selected" : ""))
      html << '</li>'
      
      html <<  '<li>'
      html << link_to('Users',{:controller=>'users',:action=>'index'},:class=>(current_page?(:controller=>'users',:action=>'index') ? "users selected" : ""))
      html << '</li>'

     end 
    html.html_safe
  end

  def student_tabs
    html = ''
      html << "<li>"
      html << link_to('Examination',{:controller=>'activetests',:action=>'index'},:class=>(controller_name.eql?('activetests') ? "activetests" : "")) 
      html << "</li>"

     html << "<li>"
      html << link_to('Services',{:controller=>'services',:action=>'index'},:class=>(controller_name.eql?('services') ? "active" : "")) 
      html << "</li>"
      
      
    html.html_safe
  end   
end

app/helpers/forgotpass_helper.rb
module ForgotpassHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/helpers/student_helper.rb
module StudentHelper
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/views/users/_form.erb
<div class="form-container">
<% form_for([@user],:html=>{:class=>'cmxf'}) do |f| %>
 <p class="legend"><strong>Note:</strong> Required fields are marked with an asterisk (<em>*</em>)</p>
<fieldset>
<%= f.error_messages %>
<div>
    <label for="name">Name<em>*</em></label>
   <%= f.text_field :name %>
  </div>
<div>
    <label for="email">email <em>*</em></label>
   <%= f.text_field :email %>
  </div>
<div>
    <label for="password">Password <em>*</em></label>
   <%= f.password_field :password %>
  </div>
<div>
    <label for="password_confirmation">Password Confirmation</label>
 <%= f.password_field :password_confirmation %>
  </div>

  <div>
    <label for="phone_number">Mobile Number</label>
 <%= f.text_field :phone_number %>
  </div>


  <div class="buttonrow">
    <%= f.submit button_name ,:class=>'button'%>
  </div>
  </fieldset>
<% end %>
</div>

app/views/users/_user.html.erb
<%content_tag_for(:tr,user) do -%>
<td><%=model_status user %></td>
<td><%= user.roles[0].name%></td>
 <td> <%= link_to h(user.name), admin_user_path(user) %></td>
 <td><%=h user.email %></td>

 <td><%=h user.phone_number %></td>

 <td><%=h User.find(user.created_by).name %></td>
 <td><%=h user.created_at.strftime('%d-%m-%Y %H:%M:%S')%></td>
 <td><%=distance_of_time_in_words_to_now(user.last_login_at, include_seconds = true)  if user.last_login_at %> ago</td>
 
 <td>
<%= link_to 'Edit', edit_admin_user_path(user) %>
</td>
<td> <%=link_to_model_status user %> 
</td> 	


 <% end %>

app/views/users/edit.html.erb
<%=render :partial=>'form',:locals=>{:button_name=>'Update',:heading=>'Edit user'} %>
<div class="bottom_links">
    <a href="/users" class="link-button">&larr; All users</a>
    <%= link_to [@user],:class=>'link-button' do %>
    Show &uarr; 
<% end %>
</div>

app/views/users/index.html.erb
<h1>List of  Users</h1>

<table id="box-table-a">
  <tr>
    <th scope="col">Name</th>
    <th scope="col">Email</th>
    <th scope="col">Actinos</th>        
  </tr>



<% @users.each do |user| %>
  <tr>
    <td><%= user.name %></td>
    <td><%= user.email %></td>
    
<td>
	<%= link_to 'View', user %> | 
    <%= link_to 'Edit', edit_user_path(user) %> | 
    <%= link_to 'Delete', user, :confirm => 'Are you sure?', :method => :delete %> | 
	<%= link_to 'Assign Examination', :controller => "userexaminations", :action=>"new", :user_id=> user.id %>

</td>
  </tr>
<% end %>
</table>

<br />

<%=link_to new_user_path,:class=>'link-button' do %>
Create New User<% end %>

app/views/users/new.html.erb
<%=render :partial=>'form',:locals=>{:button_name=>'Create',:heading=>'Create user'} %>
<br>
<div class="bottom_links">
    <a href="/users" class="link-button">&larr; List All users</a>
</div>

app/views/users/show.html.erb
<div class="form-container">
<fieldset>
<legend><b><%=@user.name %></b></legend>
<div>
   <label><b>Name:</b></label>
  <%=h @user.name %>
</div>
<hr/>
<div>
   <label><b>Email:</b></label>
  <%=h @user.email %>
</div>
<hr/>

<div>
   <label><b>Phone:</b></label>
  <%=h @user.phone_number %>
</div>
<hr/>

</fieldset>
</div>

<div class="bottom_links">
    <%= link_to edit_user_path(@user),:class=>'link-button' do %>
    Edit &uarr;
    <% end %>
    &nbsp;&nbsp;

<a href="/users" class="link-button">&larr; All Users</a>
&nbsp;&nbsp;
</div>