config/routes.rb
Lsssp::Application.routes.draw do

  resources :userexaminations

  resources :payments

  resources :examinations

  resources :questionbanks

  resources :subjects

  resources :users
  
  resources :user_sessions
  match 'login' => "user_sessions#new",      :as => :login
  match 'logout' => "user_sessions#destroy", :as => :logout
  
  resources :registrations

#  get "subjects/index"
#  get "subjects/new"
#  match "admin/subjects" => "subjects#index", :as => :subject
#  match "admin/subjects/new" =>"subjects#new", :as => :new_subject

  
  root :to => "user_sessions#new"
    
  match ':controller(/:action(/:id(.:format)))'
end

app/models/activetest.rb
class Activetest < ActiveRecord::Base

end

app/models/activexam.rb
class Activexam < ActiveRecord::Base
end

app/models/assignment.rb
class Assignment < ActiveRecord::Base
  belongs_to :user
  belongs_to :role
end

app/models/examination.rb
class Examination < ActiveRecord::Base
end

app/models/payment.rb
class Payment < ActiveRecord::Base
end

app/models/questionbank.rb
class Questionbank < ActiveRecord::Base
	belongs_to :subject
	
#	has_attached_file :question_image
end

app/models/registration.rb
class Registration < ActiveRecord::Base
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_many :assignments
  has_many :users, :through => :assignments
end

app/models/subject.rb
class Subject < ActiveRecord::Base
	has_many :questionbanks,:dependent=>:destroy
end

app/models/user.rb
class User < ActiveRecord::Base
 acts_as_authentic
  has_many :assignments
  has_many :roles, :through => :assignments


  def role_symbols
    roles.map do |role|
      role.name.underscore.to_sym
    end
  end

end

app/models/user_session.rb
class UserSession < Authlogic::Session::Base
  def to_key
    new_record? ? nil : [ self.send(self.class.primary_key) ]
  end
  
end

app/models/userexamination.rb
class Userexamination < ActiveRecord::Base
	belongs_to :examination
end

app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController
  layout "admin"
  before_filter :require_user, :only => [:index,:show, :edit, :update]
  
  def index
    @subjects = Subject.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @subjects }
    end
  end

  def show
    @subject = Subject.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @subject }
    end
  end

  def new
    @subject = Subject.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @subject }
    end
  end

  # GET /subjects/1/edit
  def edit
    @subject = Subject.find(params[:id])
  end

  def create
    @subject = Subject.new(params[:subject])

    respond_to do |format|
      if @subject.save
        format.html { redirect_to(@subject, :notice => 'Module was successfully created.') }
        format.xml  { render :xml => @subject, :status => :created, :location => @subject }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @subject.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /subjects/1
  # PUT /subjects/1.xml
  def update
    @subject = Subject.find(params[:id])

    respond_to do |format|
      if @subject.update_attributes(params[:subject])
        format.html { redirect_to(@subject, :notice => 'Module was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @subject.errors, :status => :unprocessable_entity }
      end
    end
  end

  def destroy
    @subject = Subject.find(params[:id])
    @subject.destroy

    respond_to do |format|
      format.html { redirect_to(subjects_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/activetests_helper.rb
module ActivetestsHelper
end

app/helpers/activexam_helper.rb
module ActivexamHelper
end

app/helpers/adminindex_helper.rb
module AdminindexHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  
  def admin_tabs
    html = ''
    super_admin = Role.find_by_name('super_admin')
    admin = Role.find_by_name('admin')
    if current_user.roles.include?(super_admin) 
      
      html << "<li>"
      html << link_to('Users',{:controller=>'user',:action=>'index'},:class=>(current_page?(:controller=>'user',:action=>'index') ? "users selected" : ""))
      html << "</li>"


            
    elsif current_user.roles.include?(admin) 
      
      html <<  '<li>'
      html << link_to('Module',{:controller=>'subjects',:action=>'index'},:class=>(current_page?(:controller=>'subjects',:action=>'index') ? "subjects selected" : ""))
      html << '</li>'
     
      html <<  '<li>'
      html << link_to('Examination',{:controller=>'examinations',:action=>'index'},:class=>(current_page?(:controller=>'examinations',:action=>'index') ? "examinations selected" : ""))
      html << '</li>'
      
      html <<  '<li>'
      html << link_to('Payment',{:controller=>'payments',:action=>'index'},:class=>(current_page?(:controller=>'payments',:action=>'index') ? "payments selected" : ""))
      html << '</li>'
      
      html <<  '<li>'
      html << link_to('Users',{:controller=>'users',:action=>'index'},:class=>(current_page?(:controller=>'users',:action=>'index') ? "users selected" : ""))
      html << '</li>'

     end 
    html.html_safe
  end

  def student_tabs
    html = ''
      html << "<li>"
      html << link_to('Examination',{:controller=>'activetests',:action=>'index'},:class=>(controller_name.eql?('activetests') ? "activetests" : "")) 
      html << "</li>"

     html << "<li>"
      html << link_to('Services',{:controller=>'services',:action=>'index'},:class=>(controller_name.eql?('services') ? "active" : "")) 
      html << "</li>"
      
      
    html.html_safe
  end   
end

app/helpers/examinations_helper.rb
module ExaminationsHelper
end

app/helpers/forgotpass_helper.rb
module ForgotpassHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/helpers/student_helper.rb
module StudentHelper
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/views/subjects/_form.html.erb
<div class="form-container">
<%= form_for(@subject) do |f| %>
 <p class="legend"><strong>Note:</strong> Required fields are marked with an asterisk (<em>*</em>)</p>

<%=f.error_messages%>
        <div>
            <label for="name">
                Name <em>*</em>
            </label>
            <%= f.text_field :name %>
        </div>
      <div>
            <label for="description ">
                Description <em>*</em>
            </label>
            <%= f.text_area :description ,:cols=>28,:rows=>5 %>
      </div>
      <div class="buttonrow">
  <%= f.submit "Create" %>
      </div>

<% end %>
</div>

app/views/subjects/edit.html.erb
<h1>Edit Module</h1>

<%= render 'form' %>

<div class="bottom_links">
<%= link_to 'All Modules', subjects_path ,:class=>'link-button'%>
<%= link_to 'View', @subject ,:class=>'link-button' %>
</div>

app/views/subjects/index.html.erb
<h1>List Modules</h1>
<%if @subjects.blank?%>
<b>There are No Examinations yet..!</b> 
<%else%>
<table id="box-table-a">
  <tr>
    <th scope="col">Module</th>
    <th scope="col">Actions</th>
  </tr>

<% @subjects.each do |subject| %>
  <tr>
    <td><%= subject.name %></td>
    <td><%= link_to 'View', subject %> | 
        <%= link_to 'Edit', edit_subject_path(subject) %> | 
        <%= link_to 'Delete', subject, :confirm => 'Are you sure?', :method => :delete %> |	<%= link_to 'Create Question Bank', :controller => "questionbanks", :action=>"new", :module_id=>subject.id %>
        
        </td>
  </tr>
<% end %>
</table>
<% end %>
<br />

<%= link_to 'New Module', new_subject_path,:class=>'link-button' %>

app/views/subjects/new.html.erb
<h1>New Module</h1>

<%= render 'form' %>

app/views/subjects/show.html.erb
<div class="form-container">
    <fieldset>
        <div>
            <label>
                <b>Name:</b>
            </label>
            <%=h @subject.name %>
        </div>
        <hr/>
        <div>
            <label>
                <b>Description:</b>
            </label>
            <%=h @subject.description %>
        </div>
        <hr/>

    </fieldset>
</div>

<div class="bottom_links">
    <a href="/subjects" class="link-button">&larr; All Modules</a>
    &nbsp;&nbsp;
    <%= link_to edit_subject_path(@subject),:class=>'link-button' do %>
    Edit &uarr;
    <% end %>
    &nbsp;&nbsp;
    <%=link_to new_subject_path,:class=>'link-button' do %>
    Create New Module &rarr;
    <% end %>
</div>