config/routes.rb
Lsssp::Application.routes.draw do

  resources :userexaminations

  resources :payments

  resources :examinations

  resources :questionbanks

  resources :subjects

  resources :users
  
  resources :user_sessions
  match 'login' => "user_sessions#new",      :as => :login
  match 'logout' => "user_sessions#destroy", :as => :logout
  
  resources :registrations

#  get "subjects/index"
#  get "subjects/new"
#  match "admin/subjects" => "subjects#index", :as => :subject
#  match "admin/subjects/new" =>"subjects#new", :as => :new_subject

  
  root :to => "user_sessions#new"
    
  match ':controller(/:action(/:id(.:format)))'
end

app/models/activetest.rb
class Activetest < ActiveRecord::Base

end

app/models/activexam.rb
class Activexam < ActiveRecord::Base
end

app/models/assignment.rb
class Assignment < ActiveRecord::Base
  belongs_to :user
  belongs_to :role
end

app/models/examination.rb
class Examination < ActiveRecord::Base
end

app/models/payment.rb
class Payment < ActiveRecord::Base
end

app/models/questionbank.rb
class Questionbank < ActiveRecord::Base
	belongs_to :subject
	
#	has_attached_file :question_image
end

app/models/registration.rb
class Registration < ActiveRecord::Base
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_many :assignments
  has_many :users, :through => :assignments
end

app/models/subject.rb
class Subject < ActiveRecord::Base
	has_many :questionbanks,:dependent=>:destroy
end

app/models/user.rb
class User < ActiveRecord::Base
 acts_as_authentic
  has_many :assignments
  has_many :roles, :through => :assignments


  def role_symbols
    roles.map do |role|
      role.name.underscore.to_sym
    end
  end

end

app/models/user_session.rb
class UserSession < Authlogic::Session::Base
  def to_key
    new_record? ? nil : [ self.send(self.class.primary_key) ]
  end
  
end

app/models/userexamination.rb
class Userexamination < ActiveRecord::Base
	belongs_to :examination
end

app/helpers/activetests_helper.rb
module ActivetestsHelper
end

app/helpers/activexam_helper.rb
module ActivexamHelper
end

app/helpers/adminindex_helper.rb
module AdminindexHelper
end

app/helpers/forgotpass_helper.rb
module ForgotpassHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/helpers/student_helper.rb
module StudentHelper
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/views/common/_footer.html.erb
<div id="footer">
   © 2011
</div>
</body>
</html>

app/views/common/_header.html.erb
 <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
    <head>
        <title>LSSSP</title>
        <%= javascript_include_tag 'application','jquery-1.5.2.min','rails' %>
        <%= stylesheet_link_tag 'admin_screen'%>
        <%= csrf_meta_tag %>
    </head>
    <body id="store">
        <div id="header">
            <div id="welcome">
                Welcome,<span id="welcome_username"><%=current_user.name %></span>
                <span>!&nbsp;&nbsp;</span>
                |<%=link_to 'Profile',:controller=>'/student',:action=>'show',:id=>current_user.id %>
                |  <%=link_to 'Logout',logout_path %>
            </div>
             <%=link_to image_tag("adminlogo.png"),root_url %>

        </div>
        <div id="tabs">
            <ul>
                <%= student_tabs %>
            </ul>
        </div>

app/views/common/_import_flash.html.erb
<div id="flash_messages">
  <%- flash.each do |name, msg| -%>
     <%= content_tag :div, msg, :id => "flash_#{name}",:class =>"flash_#{name}" %>
  <%- end -%>
</div>
